package com.epam.mobile.service.parser;

public enum TariffTagName {
    NAME, DESCRIPTION, IN_ARCHIVE, SUBSCRIPTION_FEE, NUM_SUBSCRIBER,
    FREE_MINUTE, COST_MINUTE, FREE_SMS, COST_SMS, FREE_INTERNET, COST_INTERNET,
    FREE_COLLEAGUE_MINUTE, COST_COLLEAGUE_MINUTE,
    FREE_INTERNATIONAL_MINUTE, COST_INTERNATIONAL_MINUTE,
    TARIFF, TARIFFS, TYPE, CORPORATE_TARIFF
}